#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_sparks/version.py`)
SPARKS_ELECTRUM_VERSION=${VERSION_STRING[2]}
SPARKS_ELECTRUM_VERSION=${SPARKS_ELECTRUM_VERSION#\'}
SPARKS_ELECTRUM_VERSION=${SPARKS_ELECTRUM_VERSION%\'}
export SPARKS_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_sparks/version.py`)
SPARKS_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
SPARKS_ELECTRUM_APK_VERSION=${SPARKS_ELECTRUM_APK_VERSION#\'}
SPARKS_ELECTRUM_APK_VERSION=${SPARKS_ELECTRUM_APK_VERSION%\'}
export SPARKS_ELECTRUM_APK_VERSION
